[package]
name = "probonotes"
version = "0.1.6"
entrypoint = "lib.typ"
authors = ["BoBozick"]
license = "MIT"
description = "Styling mathematical notes with theorem environments and mathematical notation."
keywords = ["style", "styling", "notes", "math", "mathematics", "physics", "stem", "notation", "theorem", "environment"]
disciplines = ["computer-science", "engineering", "mathematics", "physics", "education"]
categories = ["components"]
compiler = "0.14.0"