[package]
name = "probonotes"
version = "0.1.1"
entrypoint = "lib.typ"
authors = ["BoBozick"]
license = "MIT"
description = "Style for mathematical notes with theorem environment and mathematical notation."
keywords = ["style", "styling", "notes", "math", "mathematics",  "notation", "theorem", "environment"]
disciplines = ["computer-science", "engineering", "mathematics", "physics", "education"]
categories = ["components"]
compiler = "0.14.0"